#version: '3.8'
#services:
#  postgres-db:
#    image: postgres:latest
#    container_name: postgres-container
#    environment:
#      POSTGRES_DB: wattwise
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    networks:
#      - wattwise-network
#  java-app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres-db
#    networks:
#      - wattwise-network
#networks:
#  wattwise-network:
#
#volumes:
#  pg_data:
